config/routes.rb
Pinteresting::Application.routes.draw do

  devise_for :users
root "pages#home"
get "about" => "pages#about"
get "contact" => "pages#contact"
get "login" => "pages#login"
get "signup" => "pages#signup"
get "university" => "pages#university"
get "mybuzz" => "pages#mybuzz"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about 
  end

  def contact
  end

  def login
  end

  def mybuzz
  end

  def university
  end

  def signup
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<head>
<%= favicon_link_tag 'favicon.ico' %>
</head>
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
  <img src="/assets/geohive.png" alt="Logo"/>
    <ul class="nav navbar-nav navbar-right">
      <li id="nav"><%= link_to "Home", root_path %></li>
      <li id="nav"><%= link_to "About", about_path %></li>
       <li id="nav"><%= link_to "University", university_path %></li>
       <li id="nav"><%= link_to "My Buzz", mybuzz_path %></li>
      <li id="nav"><%= link_to "Contact", contact_path %></li>



         <li id= "user"><%= link_to "Sign up", signup_path, class: "btn btn-link btn-sm" %></li>
         <li id= "user"><%= link_to "Log in", login_path, class: "btn btn-link btn-sm" %></li>
      
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<style>
img {
  width:3%;
  margin-top:2px;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Hive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

		<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<h4> The Hive is a student-made, student-maintained, and student-run resource for other students. College experiences vary from campus to campus and city to city. We want to create a place where students are able to make comments and rate their experiences with different areas of college life, such as academics, as well as social life, to provide an encompassing account of what their college is like. </h4>


<div class="row">
	<div class="col-md-4">
		<img src="public/assets/bob.png" alt="Bobby" class="img-rounded"/>
		<h4>Zexi Zhang came up with this idea when he realized how veiled a college's experience may seem to others. As a student at UC Davis, he felt that he should inform others about the college as well as the city. He enjoys spending his weekends awake for 36 hours at a time at hackathons. He also enjoys design. </h4>
	</div>
	<div class="col-md-4">
		<img src="public/assets/jay.png" alt="Jay" class="img-rounded"/>
		<h4> Jay Chittoor is a student at UCLA studying developmental biology. He is also an avid coder during the weekends. He loves the outdoors and spending his free time in the wilderness, where he can contemplate about life.</h4>
	</div>
	<div class="col-md-4">
		<img src="public/assets/ju.png" alt="Juyea" class="img-rounded"/>
		<h4> Juyea Hoo studies Chemical Engineering at UCLA but has a deep passion in computers. She spends her free time learning the latest coding practices and languages while spending the rest of her time coming up with new and creative cooking recipes. </h4>
	</div>
</div>

      
<style> 
.img-rounded {
	width:250px;
	padding:20px;
	display:inline;
	margin:10px;

}
</style>

app/views/pages/contact.html.erb
<div id="main-content">
	<h1> Drop us a line. We'd love to hear your comments and feedback!</h1>

</div>

<body>


</body>

app/views/pages/home.html.erb
 <head>
 <link rel="shortcut icon" href="public/assets/geohive.ico">

 <title>The Hive</title>
 <meta title =" A student grown resource for students">
  
 </head>

		<h1>THE HIVE</h1>
		<h3> The buzz around campus.</h3>


	<div id="main_wrapper">
		<form role="form">
  		<div class="form-group">
    
    <label for="exampleInputEmail1">University Name</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter university name">
  		</div>
  	</form>
  	
  		<div id="action_button">
  		<button type="button" class="btn btn-info btn-lg">Search</button>
  		</div>

  	</div>

app/views/pages/login.html.erb
<body>

	<div id="content">
		<h1 class="first-head">Welcome to The Hive</h1>
	</div>
			
	<div id ="form-wrap">

	<form role="form">
  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  	</form>

  <form role="form">
  <div class="form-group">
    <label for="exampleInputEmail1">Password</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Password">
  </div>
		</form>
 	</div>

	<div id="confirm-button">

		<button type="button" class="btn btn-primary btn-lg">Login</button>

	</div>

	</body>

app/views/pages/mybuzz.html.erb
<div id = "main-container">
	<div class="user-input"> 
		<h1 id = "club-name">Add your club or organization!</h1>

		<h4>Name of Club/Organization</h4>
		<div class="input-group">
			<input type="text" color="black" class="form-controller">
		</div>

		
		<div class="btn-group">
			<h4>Category</h4>
				  <button type="button" class="btn btn-default">Choose one</button>
				  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
				    <span class="caret"></span>
				    <span class="sr-only"></span>
				  </button>
				  <ul class="dropdown-menu" role="menu">
				    <li><a href="#">Academic</a></li>
				    <li><a href="#">Social</a></li>
				    <li><a href="#">Outreach</a></li>
				    <li><a href="#">Sports</a></li>
				    <li><a href="#">Hobbies</a></li>
    
  				</ul>
		</div>

		<h4>Upload a photo</h4>
	</div>

	<div class="user-description">
	
		<form role="form">
			  <div class="form-description">
			    <label for="exampleInputEmail1">Description</label>
			    <input type="email" color="black" class="form-controller1" id="exampleInputEmail1" placeholder="Tell us about your club in 200 words or less.">
			  </div>
 		 </form>

	</div>

	<div id="submit-button">
	<button type="button" class="btn btn-default">Submit!</button>



	</div>

</div>

app/views/pages/signup.html.erb
<!DOCTYPE html> 
<html lang = "en">
<head>
	<meta name ="The Hive - Search for Courses and Professors"/> 
	<title> The Hive - The Buzz on Campus</title>
	<link rel= "stylesheet" href = "signup.css" link ="text/css">
</head>

<body>

	<div id="content">
		<h1 class="first-head">Sign Up for The Hive</h1>
	</div>
			
	<div id ="form-wrap">

	<form role="form">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  	</form>

  <form role="form">
  <div class="form-group">
    <label for="exampleInputEmail1">Password</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Password">
  </div>
		</form>
  <form role="form">
  <div class="form-group">
    <label for="exampleInputEmail1">Confirm Password</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Password again">
  </div>

 		</form>
 	</div>

	<div id="confirm-button">

		<button type="button" class="btn btn-primary btn-md">Sign Up</button>

	</div>

	</body>
</html>

app/views/pages/university.html.erb
<header> 
			<div id="top-wrapper">
				<h2> University of California, Los Angeles </h2>
			</div>

		<div class="form-group">
          <input type="text" class="form-control-md" placeholder="Search">
        </div>
</header>

<body> 

	<div id="main-content">
		<div class="event-name">
			<h2 class="clubs">
				Clubs and Organizations
			</h2>
		</div>
		
		<div id="category-club">
			<ul class="club"> 
				<li>Academic</li>
				<li>Social</li>
				<li>Outreach</li>
				<li>Sports</li>
				<li>Hobbies</li>
			</ul>
		</div>

		<div id="boxes">

			<div id="left-box">

			</div>

		</div>
</body>